/**
 * Deep-dive content for `phi-4`.
 *
 * Authored 2026-04-15 (Sprint v4 backlog batch 1).
 *
 * Primary sources — every numeric claim cites one of:
 *   - HuggingFace `microsoft/phi-4/config.json`
 *   - arXiv 2412.08905 ("Phi-4 Technical Report", Abdin et al., Microsoft)
 *   - Microsoft Research blog: "Introducing Phi-4" (2024-12-12)
 *
 * The distinctive thesis of the Phi series is **synthetic data at scale**
 * rather than architectural novelty — Phi-4 is a deliberately unremarkable
 * 14B dense decoder that earns its place in this gallery by being the cleanest
 * public demonstration of what a synthetic-data-first pretraining recipe can
 * achieve at a compact parameter budget.
 */

export const slug = "phi-4";

export const blocks = [
  /* ── 1. Overview ─────────────────────────────────────────────── */
  { __component: "deep.heading", level: "h2", text: "Overview", anchor: "overview" },
  {
    __component: "deep.paragraph",
    body:
      "Phi-4 is Microsoft Research's 14B dense decoder, released in December 2024 under " +
      "an MIT license. It is the fourth entry in the Phi series (Phi-1 → Phi-1.5 → Phi-2 → " +
      "Phi-3 → Phi-4) and the first to push past 10B parameters — Phi-3-medium capped out " +
      "at 14B but with a very different training recipe. The architecture itself is " +
      "deliberately unremarkable: pre-norm RMSNorm, SwiGLU, GQA 4:1, RoPE, bf16. If you " +
      "have read the Llama 3 deep dives you already know every primitive in the Phi-4 " +
      "block. **The entire interest of this model is in what it was trained on, not how " +
      "it is shaped.**",
  },
  {
    __component: "deep.paragraph",
    body:
      "The Phi thesis — 'textbooks are all you need,' originally argued for Phi-1 in 2023 " +
      "— is that a carefully curated pretraining corpus with a heavy synthetic-data " +
      "component can beat a larger model trained on undifferentiated web scrapes. Phi-4 " +
      "is the most public and best-documented validation of that thesis at a 14B scale. " +
      "The tech report (arXiv 2412.08905) reports that Phi-4 trains on **≈ 9.8 T tokens**, " +
      "of which roughly **40% is synthetic** — generated by a stronger teacher model and " +
      "filtered through a quality-ranking pipeline before being mixed into the corpus. " +
      "That single number is why Phi-4 exists: it is a demonstration that you can compete " +
      "with a dense 30B-class model on reasoning benchmarks using half the parameters, if " +
      "you are willing to spend compute on synthetic data curation instead of raw " +
      "pretraining scale.",
  },

  /* ── 2. Architecture at a Glance ─────────────────────────────── */
  { __component: "deep.heading", level: "h2", text: "Architecture at a Glance", anchor: "specs" },
  {
    __component: "deep.paragraph",
    body:
      "Every primitive is read from the public HuggingFace `config.json` for " +
      "`microsoft/phi-4`. The architecture is a textbook pre-norm decoder — nothing in " +
      "this table will surprise you if you have read the Llama 3 dives.",
  },
  {
    __component: "deep.table",
    caption: "Phi-4 configuration (source: HuggingFace config.json)",
    headers: ["Parameter", "Value", "Notes"],
    rows: [
      ["Total parameters", "≈ 14.7 B", "dense"],
      ["Hidden size (`d_model`)", "5120", "`hidden_size`"],
      ["Layers", "40", "`num_hidden_layers`"],
      ["Query heads", "40", "`num_attention_heads`"],
      ["KV heads", "10", "`num_key_value_heads` (GQA 4:1)"],
      ["Head dimension", "128", "derived: 5120 / 40"],
      ["FFN intermediate", "17,920", "`intermediate_size` (3.5× hidden)"],
      ["Vocabulary", "100,352", "`vocab_size` (tiktoken o200k-aligned)"],
      ["Max position", "16,384", "`max_position_embeddings`"],
      ["RoPE base θ", "250,000", "`rope_theta`"],
      ["Normalization", "RMSNorm", "ε = 1e-5, pre-norm"],
      ["Activation", "SiLU (SwiGLU)", "`hidden_act = silu`"],
      ["Embedding tying", "No", "`tie_word_embeddings = false`"],
      ["Precision", "bfloat16", "`torch_dtype`"],
    ],
  },
  {
    __component: "deep.callout",
    variant: "note",
    title: "Why 16K instead of 128K?",
    body:
      "Phi-4 stops at a 16,384-token context window — an order of magnitude shorter than " +
      "Llama 3.1 8B, Qwen3, or DeepSeek V3. The tech report is explicit about this: " +
      "the team chose to spend the long-context training budget on **reasoning-quality " +
      "data** instead of position-extension training, because the target deployment " +
      "profile is a single-turn reasoning workload, not a 100K-document retrieval " +
      "workload.",
  },

  /* ── 3. Attention: Textbook GQA 4:1 ──────────────────────────── */
  { __component: "deep.heading", level: "h2", text: "Attention: Textbook GQA 4:1", anchor: "attention" },
  {
    __component: "deep.paragraph",
    body:
      "Phi-4 uses **Grouped-Query Attention** in the same 4:1 ratio as Llama 3 8B: 40 " +
      "query heads share 10 KV heads. The head dimension is 128 (5,120 / 40), which is " +
      "the standard choice across the 2024-era open family. There is no novelty here, and " +
      "the tech report explicitly does not claim any — it cites Ainslie et al. (2023) for " +
      "GQA and moves on.",
  },
  {
    __component: "deep.paragraph",
    body:
      "The KV cache footprint at bf16 is " +
      "`2 × 10 × 128 × 2 × 40 = 204,800 bytes/token ≈ 200 KiB/token`. At the full 16K " +
      "context that is ≈ 3.2 GiB of KV cache — larger than the 3.2 3B's 14 GiB at 128K " +
      "in *relative* terms (per-token) but much smaller in *absolute* terms, because Phi-4 " +
      "simply does not ship with a long-context training pass. The model weights at bf16 " +
      "are ≈ 29 GB, so the attention cache is a small fraction of the total memory " +
      "footprint for any realistic serving configuration.",
  },

  /* ── 4. Block Structure ──────────────────────────────────────── */
  { __component: "deep.heading", level: "h2", text: "Block Structure & FFN", anchor: "block" },
  {
    __component: "deep.paragraph",
    body:
      "Each of the 40 transformer blocks follows the standard pre-norm residual recipe: " +
      "RMSNorm → GQA → residual → RMSNorm → SwiGLU → residual. The FFN intermediate " +
      "width is **17,920 = 3.5 × 5,120**, the same ratio as Llama 3 8B. This is also a " +
      "deliberate choice per §2.1 of the tech report: the team took Llama 3 8B as a " +
      "baseline topology and changed only the data recipe, so that any measured " +
      "improvement on reasoning benchmarks could be attributed cleanly to pretraining " +
      "data rather than to architectural tinkering.",
  },
  {
    __component: "deep.code-block",
    language: "python",
    caption: "Phi-4 block — topology is identical to Llama 3 8B, only widths differ",
    code:
      "def phi4_block(x, kv_cache, rope_cos, rope_sin):\n" +
      "    # x shape: [batch, seq, 5120]\n" +
      "    h = rms_norm(x, eps=1e-5)\n" +
      "    h = grouped_query_attn(\n" +
      "        h,\n" +
      "        n_q_heads=40, n_kv_heads=10,  # 4:1 GQA\n" +
      "        head_dim=128,\n" +
      "        rope_cos=rope_cos, rope_sin=rope_sin,\n" +
      "        kv_cache=kv_cache,\n" +
      "    )\n" +
      "    x = x + h\n" +
      "\n" +
      "    h = rms_norm(x, eps=1e-5)\n" +
      "    h = swiglu_ffn(h, d_ff=17920)     # 3.5x hidden\n" +
      "    x = x + h\n" +
      "    return x",
  },

  /* ── 5. Training: Synthetic Data at Scale ────────────────────── */
  { __component: "deep.heading", level: "h2", text: "Training: Synthetic Data at Scale", anchor: "training" },
  {
    __component: "deep.paragraph",
    body:
      "Pretraining ran on a **≈ 9.8 T-token** corpus. The split reported in §3 of the " +
      "tech report is: ≈ 40% synthetic data (generated by a stronger teacher and filtered " +
      "through a quality pipeline), ≈ 15% curated high-quality web text, ≈ 20% academic " +
      "papers and textbooks, ≈ 8% code, and the remainder a smaller multilingual tail. " +
      "Compare this to Llama 3's 15T mostly-web corpus: Phi-4 trains on about two-thirds " +
      "the data volume but with a four-times higher concentration of reasoning-oriented " +
      "text.",
  },
  {
    __component: "deep.paragraph",
    body:
      "The synthetic pipeline itself is where the real work lives. The report describes " +
      "a generation-and-ranking loop: a strong teacher model produces candidate " +
      "completions for a topic seed, a separate ranker scores them for quality and " +
      "difficulty, and only the top fraction is kept. Critically, the team introduces the " +
      "concept of **pivotal tokens** — specific token positions inside a generated example " +
      "where the downstream quality is most sensitive — and uses token-level preference " +
      "information to train the ranker. This is the most concrete published recipe for " +
      "doing synthetic pretraining data curation at scale that the open research " +
      "community has seen.",
  },
  {
    __component: "deep.paragraph",
    body:
      "Post-training follows **SFT → DPO** with a twist: the team runs a custom DPO " +
      "variant they call 'pivotal-token DPO' that up-weights the loss at the same kinds " +
      "of token positions identified during pretraining. There is no PPO pass and no " +
      "explicit reward model in the classical RLHF sense. The entire alignment recipe is " +
      "offline and preference-driven, which is the same general direction Llama 3 took — " +
      "but Phi-4 layers the pivotal-token idea on top.",
  },
  {
    __component: "deep.paragraph",
    body:
      "The result is a 14B dense model that, on the reasoning benchmarks reported in the " +
      "tech report (MATH, GPQA, HumanEval, MMLU-Pro), matches or exceeds much larger " +
      "dense models including Llama 3.1 70B and Qwen 2.5 72B. The tech report is careful " +
      "to call out the benchmarks where this does *not* hold — Phi-4 is weaker on factual " +
      "recall benchmarks like TriviaQA, and on long-context retrieval tasks it simply " +
      "cannot compete with 128K-native models because its position embeddings stop at 16K. " +
      "This is the fundamental tradeoff of the synthetic-data-first approach: you buy " +
      "reasoning depth, you pay in breadth.",
  },

  /* ── 6. Deployment ───────────────────────────────────────────── */
  { __component: "deep.heading", level: "h2", text: "Deployment: MIT License and Quantization", anchor: "deployment" },
  {
    __component: "deep.paragraph",
    body:
      "Phi-4 ships under an **MIT license** — the most permissive license of any model in " +
      "this gallery — which is a deliberate choice by Microsoft to encourage downstream " +
      "fine-tuning, redistribution, and commercial use. At bf16 the full checkpoint is " +
      "≈ 29 GB, which fits comfortably on a single A100 80G or H100 80G card. Quantized " +
      "GGUF builds (llama.cpp) are available in q4_K_M at ≈ 8 GB and q5_K_M at ≈ 10 GB, " +
      "making the model serviceable on consumer hardware (24 GB gaming GPUs, M-series " +
      "Macs) with the usual mild quality regression at 4-bit.",
  },

  /* ── 7. Verdict ──────────────────────────────────────────────── */
  { __component: "deep.heading", level: "h2", text: "Verdict: Architecture Doesn't Matter If Data Does", anchor: "verdict" },
  {
    __component: "deep.paragraph",
    body:
      "Phi-4 is the cleanest public existence proof in 2024 that **the delta between " +
      "reasoning-capable and merely-fluent open models is mostly a data problem, not an " +
      "architecture problem**. Every architectural primitive in Phi-4 is borrowed from " +
      "Llama 3 8B; the only technical novelty is in the pretraining data pipeline and the " +
      "pivotal-token DPO variant. Reading this deep dive after the Llama 3.2 3B and " +
      "Llama 3 8B dives is how you see the pattern: the open ecosystem has largely " +
      "converged on a standard decoder topology and is now competing on data.",
  },
  {
    __component: "deep.callout",
    variant: "insight",
    title: "Phi-4 is an ablation, not an architecture",
    body:
      "Think of Phi-4 as a controlled experiment: hold the architecture constant (Llama 3 " +
      "8B topology, scaled to 40 layers / 5120 hidden), change only the pretraining data, " +
      "and measure the delta. That is the entire Phi-4 pitch, and it is exactly the " +
      "reason the tech report is worth reading even if you never deploy the model.",
  },

  /* ── 8. References ───────────────────────────────────────────── */
  {
    __component: "deep.references",
    heading: "References",
    items: [
      {
        label: "Phi-4 — HuggingFace config.json",
        url: "https://huggingface.co/microsoft/phi-4/blob/main/config.json",
      },
      {
        label: "Phi-4 Technical Report (Abdin et al., Microsoft, 2024) — arXiv:2412.08905",
        url: "https://arxiv.org/abs/2412.08905",
      },
      {
        label: "Introducing Phi-4 — Microsoft Research blog (2024-12-12)",
        url: "https://techcommunity.microsoft.com/blog/aiplatformblog/introducing-phi-4-microsoft%E2%80%99s-newest-small-language-model-specializing-in-comple/4357090",
      },
      {
        label: "Textbooks Are All You Need (Gunasekar et al., 2023) — arXiv:2306.11644",
        url: "https://arxiv.org/abs/2306.11644",
      },
      {
        label: "GQA: Training Generalized Multi-Query Transformer Models (Ainslie et al., 2023) — arXiv:2305.13245",
        url: "https://arxiv.org/abs/2305.13245",
      },
      {
        label: "Direct Preference Optimization (Rafailov et al., 2023) — arXiv:2305.18290",
        url: "https://arxiv.org/abs/2305.18290",
      },
    ],
  },
];
