import type { NextConfig } from "next";

const cmsUrl = process.env.NEXT_PUBLIC_CMS_URL;
const cmsRemotePattern = (() => {
  if (!cmsUrl) return null;
  try {
    const url = new URL(cmsUrl);
    return {
      protocol: url.protocol.replace(":", "") as "http" | "https",
      hostname: url.hostname,
      port: url.port || "",
      pathname: "/uploads/**",
    };
  } catch {
    return null;
  }
})();

const nextConfig: NextConfig = {
  images: {
    qualities: [75, 90],
    remotePatterns: cmsRemotePattern ? [cmsRemotePattern] : [],
    localPatterns: [
      {
        pathname: "/media/hero/**",
      },
      {
        pathname: "/media/hero/**",
        search: "?v=*",
      },
      {
        pathname: "/media/podcast/**",
      },
      {
        pathname: "/media/podcast/**",
        search: "?v=*",
      },
    ],
  },
  async redirects() {
    return [
      // MCP slug migrations — generated by scripts/fix-mcp-slugs.mjs
      { source: "/aixcelerator/mcp/mcp-server", destination: "/aixcelerator/mcp/adadvisor-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/mcp-aktools", destination: "/aixcelerator/mcp/aktools-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/server-1xtqyei", destination: "/aixcelerator/mcp/amazon-ecs-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/server-1xtqyed", destination: "/aixcelerator/mcp/amazon-eks-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/mcp-oc1zi8", destination: "/aixcelerator/mcp/auteng-mcp-markdown-publishing-document-share", permanent: true },
      { source: "/aixcelerator/mcp/mcp-datalink", destination: "/aixcelerator/mcp/datalink", permanent: true },
      { source: "/aixcelerator/mcp/mcp-oc1zms", destination: "/aixcelerator/mcp/datamerge-mcp", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl41m", destination: "/aixcelerator/mcp/dock-ai", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl41n", destination: "/aixcelerator/mcp/dock-ai-1", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl3rn", destination: "/aixcelerator/mcp/flaim-fantasy-sports-ai-connector", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl3rw", destination: "/aixcelerator/mcp/flaim-fantasy", permanent: true },
      { source: "/aixcelerator/mcp/mcp-gmail", destination: "/aixcelerator/mcp/gmail-1", permanent: true },
      { source: "/aixcelerator/mcp/mcp-drive", destination: "/aixcelerator/mcp/google-drive", permanent: true },
      { source: "/aixcelerator/mcp/mcp-sheets", destination: "/aixcelerator/mcp/google-sheets", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl3w4", destination: "/aixcelerator/mcp/himalayas-remote-jobs", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl3w5", destination: "/aixcelerator/mcp/himalayas-remote-jobs-1", permanent: true },
      { source: "/aixcelerator/mcp/mcp-komodo", destination: "/aixcelerator/mcp/komodo-mcp-server-1", permanent: true },
      { source: "/aixcelerator/mcp/mcp-learning", destination: "/aixcelerator/mcp/learning-model-context-protocol", permanent: true },
      { source: "/aixcelerator/mcp/mcp-factorial", destination: "/aixcelerator/mcp/mcp-factorialhr", permanent: true },
      { source: "/aixcelerator/mcp/mcp-openclaw", destination: "/aixcelerator/mcp/mcp-openclaw-extensions", permanent: true },
      { source: "/aixcelerator/mcp/mcp-windbg", destination: "/aixcelerator/mcp/mcp-server-for-windbg-crash-analysis", permanent: true },
      { source: "/aixcelerator/mcp/mcp-oc1zot", destination: "/aixcelerator/mcp/mailjunky", permanent: true },
      { source: "/aixcelerator/mcp/mcp-oc1zlx", destination: "/aixcelerator/mcp/marketcore", permanent: true },
      { source: "/aixcelerator/mcp/mcp-oc1zos", destination: "/aixcelerator/mcp/marketcore-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/mcp-oc1zlw", destination: "/aixcelerator/mcp/marketcore-mcp-server-1", permanent: true },
      { source: "/aixcelerator/mcp/mcp-notify", destination: "/aixcelerator/mcp/notify-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/mcp-oc1znn", destination: "/aixcelerator/mcp/obris", permanent: true },
      { source: "/aixcelerator/mcp/mcp-oc1znm", destination: "/aixcelerator/mcp/obris-1", permanent: true },
      { source: "/aixcelerator/mcp/mcp-outline", destination: "/aixcelerator/mcp/outline-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/mcp-outlook", destination: "/aixcelerator/mcp/outlook", permanent: true },
      { source: "/aixcelerator/mcp/mcp-redis", destination: "/aixcelerator/mcp/redis-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/mcp-refactoring", destination: "/aixcelerator/mcp/refactoring-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/mcp-relay", destination: "/aixcelerator/mcp/relay", permanent: true },
      { source: "/aixcelerator/mcp/mcp-oc1zsd", destination: "/aixcelerator/mcp/scite", permanent: true },
      { source: "/aixcelerator/mcp/mcp-stata", destination: "/aixcelerator/mcp/stata-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/mcp-statcan", destination: "/aixcelerator/mcp/statistics-canada-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/server-template", destination: "/aixcelerator/mcp/template-server-1", permanent: true },
      { source: "/aixcelerator/mcp/mcp-template", destination: "/aixcelerator/mcp/template-server-2", permanent: true },
      { source: "/aixcelerator/mcp/mcp-toleno", destination: "/aixcelerator/mcp/toleno-network", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl3th", destination: "/aixcelerator/mcp/trade-it", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl41p", destination: "/aixcelerator/mcp/trilo", permanent: true },
      { source: "/aixcelerator/mcp/mcp-youtube", destination: "/aixcelerator/mcp/youtube-data", permanent: true },
      { source: "/aixcelerator/mcp/mcp-oc1zoj", destination: "/aixcelerator/mcp/llmse-mcp", permanent: true },
      { source: "/aixcelerator/mcp/mcp-bf1do6", destination: "/aixcelerator/mcp/meetlark-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/mcp-1n9ugzb", destination: "/aixcelerator/mcp/meetlark-mcp-server-1", permanent: true },
      { source: "/aixcelerator/mcp/mcp-oc1zsa", destination: "/aixcelerator/mcp/rolli-mcp", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpkzw3", destination: "/aixcelerator/mcp/tickettailor-mcp", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpkzvg", destination: "/aixcelerator/mcp/waystation-mcp", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl3ub", destination: "/aixcelerator/mcp/websitepublisher-mcp", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl3rk", destination: "/aixcelerator/mcp/zine-mcp", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl3rr", destination: "/aixcelerator/mcp/zine-mcp-1", permanent: true },
      { source: "/aixcelerator/mcp/server-1xtqyga", destination: "/aixcelerator/mcp/certman-server", permanent: true },
      { source: "/aixcelerator/mcp/server-1xtqyg9", destination: "/aixcelerator/mcp/certman-server-1", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl3w6", destination: "/aixcelerator/mcp/himalayas-mcp", permanent: true },
      { source: "/aixcelerator/mcp/mcp-ccmpj6", destination: "/aixcelerator/mcp/thoughtspot-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/mcp-1ybkaqo", destination: "/aixcelerator/mcp/thoughtspot-mcp-server-1", permanent: true },
      { source: "/aixcelerator/mcp/mcp-1reyfnc", destination: "/aixcelerator/mcp/thoughtspot-mcp-server-2", permanent: true },
      { source: "/aixcelerator/mcp/server-1xtqyeh", destination: "/aixcelerator/mcp/trustrails-server", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl3tr", destination: "/aixcelerator/mcp/biz-icecat-mcp", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl3qp", destination: "/aixcelerator/mcp/biz-icecat-mcp-1", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl3qo", destination: "/aixcelerator/mcp/biz-icecat-mcp-2", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl3qr", destination: "/aixcelerator/mcp/biz-icecat-mcp-3", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl41l", destination: "/aixcelerator/mcp/axiom-mcp", permanent: true },
      { source: "/aixcelerator/mcp/mcp-lpl41k", destination: "/aixcelerator/mcp/contraption-mcp", permanent: true },
      { source: "/aixcelerator/mcp/mcp-nspeb4", destination: "/aixcelerator/mcp/flyweel-mcp-server", permanent: true },
      { source: "/aixcelerator/mcp/server-1xtqy6n", destination: "/aixcelerator/mcp/heyspark-mcp-server", permanent: true },
    ];
  },
  async rewrites() {
    return [
      { source: "/podcasts", destination: "/resources/podcasts" },
      { source: "/podcast/:slug", destination: "/resources/podcasts/company?slug=:slug" },
      { source: "/resources/podcasts/company/:slug", destination: "/resources/podcasts/company?slug=:slug" },
      { source: "/articles", destination: "/resources/articles" },
    ];
  },
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          {
            key: "X-Frame-Options",
            value: "SAMEORIGIN",
          },
          {
            key: "X-Content-Type-Options",
            value: "nosniff",
          },
          {
            key: "Referrer-Policy",
            value: "strict-origin-when-cross-origin",
          },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=(), interest-cohort=()",
          },
          ...(process.env.NODE_ENV === "production"
            ? [
                {
                  key: "Content-Security-Policy",
                  value: [
                    "default-src 'self'",
                    "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://www.buzzsprout.com",
                    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
                    "font-src 'self' https://fonts.gstatic.com data:",
                    `img-src 'self' data: blob: https://www.google-analytics.com https://www.googletagmanager.com ${cmsUrl ? new URL(cmsUrl).origin : ""}`.trim(),
                    `connect-src 'self' https://www.google-analytics.com https://www.googletagmanager.com https://analytics.google.com https://www.buzzsprout.com https://*.buzzsprout.com ${cmsUrl || ""}`.trim(),
                    "media-src 'self' https://www.buzzsprout.com https://*.buzzsprout.com",
                    "frame-src 'self' https://www.buzzsprout.com",
                    "frame-ancestors 'self'",
                    "base-uri 'self'",
                    "form-action 'self'",
                  ].join("; "),
                },
              ]
            : []),
        ],
      },
      {
        source: "/(.*)",
        has: [{ type: "header", key: "x-forwarded-proto", value: "https" }],
        headers: [
          {
            key: "Strict-Transport-Security",
            value: "max-age=31536000; includeSubDomains; preload",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
